FROM bellsoft/liberica-openjdk-debian:11

RUN apt-get update && apt-get install -y fontconfig fonts-dejavu && rm -rf /var/lib/apt/lists/*

ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV LANGUAGE=C.UTF-8

ENV JAVA_OPTS="-Djava.awt.headless=true -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8"

WORKDIR /app

COPY RuoYi-Vue/ruoyi-admin/target/ruoyi-admin.jar /app/ruoyi-admin.jar

CMD ["java", "-Dfile.encoding=UTF-8", "-Dsun.jnu.encoding=UTF-8", "-jar", "ruoyi-admin.jar"]